# production configuraiton
application:
  name: project-group-careless-crayfish
  mongo:
    address: 127.0.0.1:27017
    username: devroot
    password: devroot
  gemini:
    api:
      url: https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=